---
title: "Chapter 2 Exploratory Data Analysis"
author: "Chihara-Hesterberg"
date: "November 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.width="50%")
library(ggplot2)
library(dplyr)
```

###Section 2.4

```{r}
x <- c(17.7, 22.6, 26.1, 28.3, 30, 31.2, 31.5, 33.5, 34.7, 36)
df <- data.frame(x)
ggplot(df, aes(sample = x)) + stat_qq() + stat_qq_line()  
 
NCBirths <- read.csv("http://sites.google.com/site/chiharahesterberg/data2/NCBirths2004.csv")

ggplot(NCBirths, aes(sample = Weight)) + stat_qq() + stat_qq_line()

```

###Section 2.5
####R Note
```{r}
x <- c(3, 6, 15, 15, 17, 19, 24)
df <- data.frame(x)
ggplot(df, aes(x)) + stat_ecdf(geom = "step")
                             
# random sample of size 25 from N(0,1)
df <- data.frame(x = rnorm(25))

ggplot(df, aes(x)) + stat_ecdf() + stat_function(fun = pnorm, color = "red")

Beerwings <- read.csv("http://sites.google.com/site/chiharahesterberg/data2/Beerwings.csv")

ggplot(Beerwings, aes(Beer, color = Gender)) + stat_ecdf()
 
```

###Section 2.6
```{r}

ggplot(Beerwings, aes(x=Hotwings, y = Beer)) + geom_point()

ggplot(Beerwings, aes(x = Hotwings, y = Beer, color = Gender)) + geom_point()

```