---
title: "Chap 7 More Confidence Intervals"
author: "Chihara-Hesterberg"
date: "December  2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.width="50%")
library(ggplot2)
library(dplyr)
```

###Section 7.1.1 
CI for normal with known sigma
```{r, out.width="100%"}
#set.seed(1)
counter <- 0                 # set counter to 0
df <- data.frame(x=c(22,28), y = c(1,100))
p <- ggplot(df, aes(x=x, y = y)) + geom_vline(xintercept=25, colour = "red")

for (i in 1:1000)
 {
  x <- rnorm(30, 25, 4)           # draw a random sample of size 30
  L <- mean(x) - 1.96*4/sqrt(30)  # lower limit
  U <- mean(x) + 1.96*4/sqrt(30)  # upper limit
  if (L < 25 && 25 < U)           # check to see if 25 is in interval
     counter <- counter + 1       # increase counter by 1
  if (i <= 100)                   #plot first 100 intervals
  p <-    p + annotate("segment", x = L, xend=U, y = i, yend=i )  
 }

print(p)

 counter/1000    # proportion of times interval contains mu.
```

### Section 7.1.2
 Simulate distribution of t statistic
```{r}
N <- 10^4
w <- numeric(N)
n <- 15  #sample size
for (i in 1:N)
 {
  x <- rnorm(n, 25, 7)  #draw a size 15 sample from N(25, 7^2)
  xbar <- mean(x)
  s <- sd(x)
  w[i] <- (xbar-25) / (s/sqrt(n))
 }

ggplot() + geom_histogram(aes(w), bins = 12)

ggplot() + stat_qq(aes(sample = w)) + geom_abline(intercept = 0, slope = 1, colour = "red")

```


### Example 7.7 
Simulation 95% confidence interval from
skewed gamma distribution
```{r}
# set.seed(0)

tooLow <- 0           #set counter to 0
tooHigh <- 0          #sest counter to 0
n <- 20               # sample size
N <- 10^5
for (i in 1:N)
 {
  x <- rgamma(n, shape=5, rate=2)
  xbar <- mean(x)
  s <- sd(x)
  lower <- xbar - abs(qt(.025, n-1))*s/sqrt(n)
  upper <- xbar + abs(qt(.025, n-1))*s/sqrt(n)
  if (upper < 5/2) tooLow <- tooLow + 1
  if (lower > 5/2) tooHigh <- tooHigh + 1
 }
tooLow/N
tooHigh/N
```


### Example 7.21 
One sample bootstrap t confidence interval

```{r}
Bangladesh <- read.csv("http://sites.google.com/site/chiharahesterberg/data2/Bangladesh.csv")
Arsenic <- pull(Bangladesh, Arsenic)
Arsenic <- Bangladesh$Arsenic

xbar <- mean(Arsenic)
N <- 10^4
n <- length(Arsenic)
Tstar <- numeric(N)
#set.seed(100)
for (i in 1:N)
 {
   x <-sample(Arsenic, size = n, replace = T)
   Tstar[i] <- (mean(x)-xbar)/(sd(x)/sqrt(n))
 }

quantile(Tstar, c(0.025, 0.975))

ggplot() + geom_histogram(aes(Tstar), bins = 12) +  labs(x= "T*", title = "Bootstrap distribution of T*")

df <- data.frame(Tstar)
ggplot(df, aes(sample = Tstar)) + stat_qq() + stat_qq_line()
```

### Exampe 7.22 Verizon
 2-Sample bootstrap t confidence interval

```{r}
Verizon <- read.csv("http://sites.google.com/site/chiharahesterberg/data2/Verizon.csv")

Time.ILEC <- Verizon %>% filter(Group == "ILEC") %>% pull(Time)
Time.CLEC <- Verizon %>% filter(Group == "CLEC") %>% pull(Time)
thetahat <- mean(Time.ILEC)-mean(Time.CLEC)
nx <- length(Time.ILEC)  #nx=1664
ny <- length(Time.CLEC)  #ny=23
SE <- sqrt(var(Time.ILEC)/nx + var(Time.CLEC)/ny)

N <- 10000
Tstar <- numeric(N)
set.seed(0)
for(i in 1:N)
 {
  bootx <- sample(Time.ILEC, nx, replace = TRUE)
  booty <- sample(Time.CLEC, ny, replace = TRUE)
  Tstar[i] <- (mean(bootx) - mean(booty) - thetahat) /
               sqrt(var(bootx)/nx + var(booty)/ny)
 }

thetahat - quantile(Tstar, c(.975, .025)) * SE

t.test(Time.ILEC, Time.CLEC)$conf
```

